Meliox/PVE-mods

.gitignore
pve-mod-gui-temp.sh

Disable hdd/ssd information automatically if not found Disable nvme information automatically if not found Remove unintended package install
To accommondate #1 and #3

Ask user for input for CPU configuration

---

pve-mod-gui-temp.sh
readme.md

Host details box are always shown in a single column using the complete window's width, regardless of the actual column count for the rest of the boxes.
CPU & drive thermal data are rearranged and displayed in groups. Group items use 2-column layout (temperatures aligned to the right) for better readability.

Host summary layout optimization

---

pve-mod-gui-temp.sh
readme.md

Implement fan speeds

---

pve-mod-gui-temp.sh
readme.md

- Rephrase thermal state to sensors output & temperatures display to sensors display
- Update supported PVE versions in readme.md

Rephrase thermal references to sensors

---

pve-mod-gui-sensors.sh
readme.md

Add support for multiple CPUs
Sanitize "sensors -j" JSON output

Extend CPU temperature readings

---

pve-mod-gui-sensors.sh
readme.md

Reference:  #39, #20, #22, #19, #16, #12, #9

Inform user to clear browser cache after successfull installation

---

pve-mod-gui-sensors.sh

Implements #45 
See review in #46

Add system information #2

---

pve-mod-gui-sensors.sh

Add an argument to save sensors data, so that it can be shared.

save-sensors-data argument

---

pve-mod-gui-sensors.sh

- Adjust prompts for:
- temperature units
- system information
- Unify letter cases and type of the feedback texts
- Format code

Unify prompt texts

---

pve-mod-gui-sensors.sh

Implement #41 
Example 1:
```
{
"asus_wmi_sensors-virtual-0": {
"Adapter": "Virtual device",
"CPU Core Voltage": {
"in0_input": 0.970
},
"+12V Voltage": {
"in1_input": 12.230
},
"+5V Voltage": {
"in2_input": 4.960
},
"3VSB Voltage": {
"in3_input": 3.314
},
"CPU Fan": {
"fan1_input": 1451.000
},
"Chassis Fan 1": {
"fan2_input": 1527.000
},
"Chassis Fan 2": {
"fan3_input": 1486.000
},
"Chassis Fan 3": {
"fan4_input": 1477.000
},
"AIO Pump": {
"fan5_input": 0.000
},
"Water Pump": {
"fan6_input": 0.000
},
"CPU OPT": {
"fan7_input": 0.000
},
"CPU Temperature": {
"temp1_input": 42.000
},
"Motherboard Temperature": {
"temp2_input": 30.000
},
"Chipset Temperature": {
"temp3_input": 44.000
},
"Tsensor 1 Temperature": {
"temp4_input": 216.000
}
},
...
}
```
Example 2:
```
{
"coretemp-isa-0000": { …
```

add support multiple Fan Speed Key Patterns

---

pve-mod-gui-sensors.sh

Add color to the prompt texts during the installation to highlight the need for user's feedback.

Color prompts

---

readme.md

Improve install instruction

---

readme.md

update supported versions to 8.3.2

---

pve-mod-gui-sensors.sh
readme.md

* Fixed to render correctly even if INTEL and AMD core nodes are mixed in the cluster.
* Fixed the behavior of forcing configuration before being told "Mod is already installed".
* Add motherboard information as an option in System Information settings.

[pve-mod-gui-sensors.sh] support for mixed core cluster

---

pve-mod-gui-sensors.sh

Regression from 3cb1ac8 as SENSORS_DETECTED is not true if sensors output only contains CPU. Resolves #85

Fix cpu detection

---

pve-mod-gui-sensors.sh

fix double detection of AMD cpus leading to wrong cpu detected

---

pve-mod-gui-sensors.sh

Verify backup files are created and identifical implements part of #94

Verify backup files are created and identifical implements part of (#94)

---

pve-mod-gui-sensors.sh
readme.md

Fix sensors JSON output to formatted version

---

pve-mod-gui-sensors.sh

Example output:
"SODIMM":{"temp3_input":34.000000},"SODIMM":{"temp4_input":39.000000},"SODIMM":{"temp5_input":44.000000},"SODIMM":{"temp6_input":33.000000}
will converted to
"SODIMM3":{"temp3_input":34.000000},"SODIMM4":{"temp4_input":39.000000},"SODIMM5":{"temp5_input":44.000000},"SODIMM6":{"temp6_input":33.000000}
fixes #113

Fix invalid JSON SODIMM sensors output from lm-sensors

---

pve-mod-gui-sensors.sh

Adds support for 2 die AMD cpu
Reference: https://github.com/Meliox/PVE-mods/issues/112#issuecomment-3204772118
```json
{
"iwlwifi_1-virtual-0": {
"Adapter": "Virtual device",
"temp1": {}
},
"nct6779-isa-0290": {
"Adapter": "ISA adapter",
"VCore": {
"in0_input": 1.152,
"in0_min": 0.4,
"in0_max": 1.456,
"in0_alarm": 0.0,
"in0_beep": 0.0
},
"VPPM": {
"in1_input": 2.544,
"in1_min": 2.368,
"in1_max": 2.624,
"in1_alarm": 0.0,
"in1_beep": 0.0
},
"AVCC": {
"in2_input": 3.328,
"in2_min": 2.976,
"in2_max": 3.632,
"in2_alarm": 0.0,
"in2_beep": 0.0
},
"3VCC": {
"in3_input": 3.328,
"in3_min": 2.976,
"in3_max": 3.632,
"in3_alarm": 0.0,
"in3_beep": 0.0
},
"+12V": {
"in4_input": 12.0912,
"in4_min": 11.4048,
"in4_max": 12.6192,
"in4_alarm": 0.0,
"in4_beep": 0.0
},
"VDDCR_SOC": {
"in5_input": 1.192, …
```

Adds support for 2 die AMD cpu
